try: #Se acontecer algum erro ele vai para except
  int('a')
  print(1234)
  print(1234)
except:
  print('Erro 404')